[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"

[pt]
  languageName = "Português"
  contentDir = "content/pt"
  weight = 15
  [pt.params]
    languageISO = "PT"